# Generated by Django 4.2 on 2025-12-20 03:47

import ckeditor.fields
import colorfield.fields
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('css_class', models.CharField(max_length=100, unique=True)),
                ('css_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Custom Style',
                'verbose_name_plural': 'Custom Styles',
            },
        ),
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('color', colorfield.fields.ColorField(default='#E9C46A', image_field=None, max_length=18, samples=None)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Guestbook Entry',
                'verbose_name_plural': 'Guestbook Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('background_image', models.ImageField(blank=True, upload_to='hero/')),
                ('overlay_opacity', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('button_text', models.CharField(default='Book Now', max_length=50)),
                ('button_link', models.CharField(default='#booking', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('enable_title_animation', models.BooleanField(default=True)),
                ('title_animation_type', models.CharField(default='fadeInUp', max_length=50)),
                ('enable_subtitle_animation', models.BooleanField(default=True)),
                ('subtitle_animation_delay', models.IntegerField(default=500)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('point_type', models.CharField(choices=[('food', 'Food & Drink'), ('entertainment', 'Entertainment'), ('culture', 'Cultural'), ('shopping', 'Shopping'), ('nature', 'Nature'), ('transport', 'Transport')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('icon', models.CharField(default='pin', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#E76F51', image_field=None, max_length=18, samples=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Neighborhood Point',
                'verbose_name_plural': 'Neighborhood Points',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('dorm', 'Dormitory'), ('private', 'Private Room'), ('suite', 'Suite'), ('family', 'Family Room')], max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='rooms/')),
                ('features', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('color_accent', colorfield.fields.ColorField(default='#2A9D8F', image_field=None, max_length=18, samples=None)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('hover_effect', models.CharField(choices=[('scale', 'Scale Up'), ('slide', 'Slide Up'), ('rotate', 'Rotate'), ('shadow', 'Shadow Lift')], default='scale', max_length=50)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['order', 'price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='734 Hotel', max_length=200)),
                ('tagline', models.CharField(default='Your basecamp for good stories', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('tripadvisor_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('primary_color', colorfield.fields.ColorField(default='#E76F51', image_field=None, max_length=18, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#2A9D8F', image_field=None, max_length=18, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#E9C46A', image_field=None, max_length=18, samples=None)),
                ('background_color', colorfield.fields.ColorField(default='#F8F9FA', image_field=None, max_length=18, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#264653', image_field=None, max_length=18, samples=None)),
                ('font_family', models.CharField(default="'Inter', sans-serif", max_length=200)),
                ('heading_font', models.CharField(default="'Cabin', sans-serif", max_length=200)),
                ('enable_animations', models.BooleanField(default=True)),
                ('animation_speed', models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', max_length=20)),
                ('enable_vibe_check', models.BooleanField(default=True)),
                ('enable_guestbook', models.BooleanField(default=True)),
                ('enable_booking', models.BooleanField(default=True)),
                ('enable_map', models.BooleanField(default=True)),
                ('layout_style', models.CharField(choices=[('standard', 'Standard'), ('minimal', 'Minimal'), ('cozy', 'Cozy')], default='cozy', max_length=50)),
                ('custom_css', models.TextField(blank=True)),
                ('notification_email', models.EmailField(default='admin@734hotel.com', max_length=254)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='VibeCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vibe_check/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('guest_note', models.TextField(blank=True)),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('guest_country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vibe Check Item',
                'verbose_name_plural': 'Vibe Check Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('tripadvisor', 'TripAdvisor'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok')], max_length=20, unique=True)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('site_settings', models.ForeignKey(blank=True, help_text='Link to site settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='website.sitesettings')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking', 'New Booking'), ('contact', 'New Contact Message'), ('guestbook', 'New Guestbook Entry'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('admin_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_country', models.CharField(blank=True, max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.IntegerField(default=1)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_replies', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='website.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=100, unique=True)),
                ('animation_type', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('bounce', 'Bounce'), ('rotate', 'Rotate'), ('flip', 'Flip')], max_length=20)),
                ('duration', models.IntegerField(default=1000)),
                ('delay', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('site_settings', models.ForeignKey(blank=True, help_text='Link to site settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animation_settings', to='website.sitesettings')),
            ],
            options={
                'verbose_name': 'Animation Setting',
                'verbose_name_plural': 'Animation Settings',
            },
        ),
    ]
