# Generated by Django 4.2 on 2026-02-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cachesetting_event_language_newslettersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('sqlite', 'SQLite (Default)'), ('postgresql', 'PostgreSQL')], default='sqlite', max_length=20)),
                ('sqlite_name', models.CharField(blank=True, default='db.sqlite3', max_length=255)),
                ('postgres_name', models.CharField(blank=True, max_length=255)),
                ('postgres_user', models.CharField(blank=True, max_length=255)),
                ('postgres_password', models.CharField(blank=True, max_length=255)),
                ('postgres_host', models.CharField(blank=True, max_length=255)),
                ('postgres_port', models.CharField(blank=True, default='5432', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Database Configuration',
                'verbose_name_plural': 'Database Configurations',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-concierge-bell', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='booking_sms_template',
            field=models.TextField(blank=True, default='Hi there, your booking at 734 Hotel is confirmed. We will contact you soon with details.'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('plivo', 'Plivo'), ('nexmo', 'Nexmo/Vonage'), ('arkesel', 'Arkesel'), ('custom', 'Custom API')], default='twilio', max_length=20),
        ),
    ]
