# Generated by Django 4.2 on 2026-02-27 23:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_databaseconfig_serviceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply_history',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
