# Generated by Django 4.2 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contactmessage_reply_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='motion_intensity',
            field=models.CharField(choices=[('soft', 'Soft'), ('balanced', 'Balanced'), (
                'strong', 'Strong')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scroll_smoothness',
            field=models.CharField(choices=[('gentle', 'Gentle'), ('normal', 'Normal'), (
                'enhanced', 'Enhanced')], default='normal', max_length=20),
        ),
    ]
