# Generated by Django 4.2 on 2026-02-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_sitesettings_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_datepicker',
            field=models.BooleanField(default=True),
        ),
    ]
