# Generated by Django 4.2 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_sitesettings_enable_datepicker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(
                    help_text='Use URL path only. Example: / for homepage, /room/ for all room pages.', max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Path Match'), (
                    'prefix', 'Path Prefix Match')], default='exact', max_length=10)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('og_title', models.CharField(blank=True, max_length=90)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(
                    blank=True, null=True, upload_to='logos/')),
                ('twitter_card', models.CharField(
                    default='summary_large_image', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(
                    default=100, help_text='Lower number = higher priority when multiple prefix rules match.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page Rule',
                'verbose_name_plural': 'SEO Page Rules',
                'ordering': ['priority', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='seopage',
            constraint=models.UniqueConstraint(
                fields=('path', 'match_type'), name='unique_seo_path_match_type'),
        ),
    ]
