# Generated by Django 4.2 on 2026-03-02 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_seopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_access_token',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('paypal', 'PayPal'), (
                    'momo', 'Mobile Money (Custom URL/API)'), ('custom', 'Custom Provider')], max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('api_base_url', models.URLField(blank=True)),
                ('callback_url', models.URLField(blank=True)),
                ('checkout_url_template', models.TextField(
                    blank=True, help_text='For momo/custom: use placeholders {amount}, {amount_minor}, {email}, {reference}, {currency}, {callback_url}.')),
                ('extra_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Payment Provider',
                'verbose_name_plural': 'Payment Providers',
                'ordering': ['priority', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_online_payment', models.BooleanField(default=False)),
                ('auto_confirm_booking_on_payment',
                 models.BooleanField(default=True)),
                ('allow_guest_changes_after_payment',
                 models.BooleanField(default=False)),
                ('default_currency', models.CharField(
                    default='GHS', max_length=10)),
                ('success_redirect_path', models.CharField(
                    default='/payment/success/', max_length=200)),
                ('cancel_redirect_path', models.CharField(
                    default='/payment/cancel/', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('external_reference', models.CharField(
                    blank=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Verification'), ('paid', 'Paid'), (
                    'failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='payments', to='website.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='payments', to='website.paymentproviderconfig')),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
